# Generated by Django 3.0.7 on 2020-07-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='deleted_added',
            new_name='date_added',
        ),
    ]
