# Generated by Django 3.1 on 2020-09-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
