# Generated by Django 3.1 on 2020-09-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
